### ISSUE TITLE
문장 구분을 위한 번호 표기

### ISSUE THREAD

**Issue by okjin** [SDSACT/zeta_issue#3]
Zeta

Please let me and my team know 1) what is causing the issues 2) what are we going to do to resolve the issues 3) how can we explain this to OPEL / PSA.
저와 제 팀에게 2호를 야기하는 것이 무엇인지 알려주시기 바랍니다3문제를 해결하기 위해 우리가 무엇을 할 것인가? opel PSA에 어떻게 설명할 수 있을까요?

vs Google

저와 제 팀이 1) 문제의 원인 2) 문제를 해결하기 위해 무엇을 할 것인지 3) 어떻게 OPEL / PSA에 설명 할 수 있는지 알려주십시오.

**Comment by rhasya** [comment]
해당 내용을 수정하여 반영하였습니다.
